import React,{useState} from 'react';
import {Linking,Share,TextInput} from 'react-native';
import {usePractice} from '../state';
import {website} from '../config';
import {Page,Heading,Title,Body,Meta,Card,Button,Notice,s} from '../ui';
export function Account(){
 const store=usePractice();const [confirm,setConfirm]=useState(false);const [exported,setExported]=useState('');const [message,setMessage]=useState('');
 const open=async(path:string)=>{try{await Linking.openURL(website+path);}catch{setMessage('Could not open your browser. Visit www.quizworld.xyz.');}};
 const exportData=async()=>{const text=JSON.stringify(store.state,null,2);setExported(text);try{await Share.share({message:text,title:'QuizWorld personal practice'});}catch{setMessage('Sharing is unavailable here. Select and copy the export below.');}};
 return <Page><Heading>Your space.</Heading><Body muted>You are practising as a guest.</Body><Notice message={store.error||message}/><Card><Title>On this device, for you</Title><Body>Checked answers, review questions and your last 100 completed sessions stay here.</Body><Meta>No account tokens, analytics, ads or uploaded study history. Local data is unencrypted; do not use this build for private student records. Uninstalling the app or clearing browser storage removes it.</Meta><Meta>Storage estimate: {(JSON.stringify(store.state).length*2/1024).toFixed(1)} KiB / 1,953 KiB local limit.</Meta></Card>
 <Card><Title>QuizWorld account</Title><Body>Native sign-in is not connected.</Body><Meta>Use your existing account on the website in your browser. This will not sign you into this app or sync this device’s practice.</Meta><Button label="Open QuizWorld website" secondary onPress={()=>{void open('/login');}}/></Card>
 <Card><Title>Study Plus · in development</Title><Body>Subscriptions are not available in this build.</Body><Meta>A seven-day trial and US$5.99/month are proposed, not an available offer. Pricing, eligibility and store configuration are not finalized.</Meta><Meta>No trial has started and no charge can be made here. Purchase, restore and subscription management will appear only after verified store billing is connected.</Meta></Card>
 <Title>Your practice data</Title><Button label="Export device practice" secondary disabled={store.busy} onPress={()=>{void exportData();}}/>
 {exported?<><Meta>Only share this with people you choose. Select and copy if your device cannot share.</Meta><TextInput accessibilityLabel="Practice export JSON" multiline editable={false} value={exported} style={s.input}/><Button label="Close export" secondary onPress={()=>setExported('')}/></>:null}
 {!confirm?<Button label="Clear device practice" secondary disabled={store.busy} onPress={()=>setConfirm(true)}/>:<Card><Title>Clear practice on this device?</Title><Body>This removes your checkpoint, review queue and local history. It does not delete your QuizWorld website account or cancel any store subscription.</Body><Button label="Confirm clear device practice" disabled={store.busy} onPress={()=>{void store.reset().then(ok=>{if(ok){setConfirm(false);setExported('');setMessage('');}});}}/><Button label="Keep my practice" secondary onPress={()=>setConfirm(false)}/></Card>}
 <Title>Privacy & support</Title><Meta>Website account deletion is a separate support process. An authenticated in-app account deletion flow is not implemented; this development build is not store-ready.</Meta><Button label="Website privacy policy" secondary onPress={()=>{void open('/privacy');}}/><Button label="Website terms" secondary onPress={()=>{void open('/terms');}}/>
 <Meta>Content issue? Use the support contact in the website privacy policy. Include the quiz title, not another learner’s data.</Meta><Meta>QuizWorld mobile · development companion · 0.1.0</Meta></Page>;
}
