defmodule QuizworldRealtime.GamesTest do
  use ExUnit.Case, async: false

  alias QuizworldRealtime.Games

  setup do
    QuizworldRealtime.TestGameStore.reset()
    :ok
  end

  defp question do
    %{
      "id" => "q1",
      "text" => "What is 2 + 2?",
      "time_limit" => 20,
      "points" => 1_000,
      "order_index" => 0,
      "answers" => [
        %{"id" => "a1", "text" => "4", "is_correct" => true},
        %{"id" => "a2", "text" => "5", "is_correct" => false}
      ]
    }
  end

  defp assert_game_stopped(pin, attempts \\ 20)

  defp assert_game_stopped(pin, attempts) when attempts > 0 do
    case Registry.lookup(QuizworldRealtime.GameRegistry, pin) do
      [] ->
        :ok

      [{pid, _value}] ->
        if Process.alive?(pid) do
          Process.sleep(10)
          assert_game_stopped(pin, attempts - 1)
        else
          :ok
        end
    end
  end

  defp assert_game_stopped(pin, 0) do
    flunk("game #{pin} restarted after normal cleanup")
  end

  defp await_restarted_game(pin, old_pid, attempts \\ 20)

  defp await_restarted_game(pin, old_pid, attempts) when attempts > 0 do
    case Registry.lookup(QuizworldRealtime.GameRegistry, pin) do
      [{pid, _value}] when pid != old_pid ->
        pid

      _ ->
        Process.sleep(10)
        await_restarted_game(pin, old_pid, attempts - 1)
    end
  end

  defp await_restarted_game(pin, _old_pid, 0) do
    flunk("game #{pin} did not restart after an abnormal exit")
  end

  test "GameServer restarts only after abnormal exits" do
    spec = QuizworldRealtime.GameServer.child_spec(%{"pin" => "SPEC01"})
    assert spec.restart == :transient
  end

  test "game instance identity is always generated by the server" do
    pin = "I" <> Integer.to_string(System.unique_integer([:positive]))

    assert {:ok, _snapshot, _host_token} =
             Games.create_session(%{
               "pin" => pin,
               "instance_id" => "client-controlled",
               "host_id" => "host_test",
               "quiz_id" => "quiz_test",
               "questions" => [question()],
               "game_mode" => "classic"
             })

    assert {:ok, stored_game} = QuizworldRealtime.TestGameStore.fetch_game(pin)
    refute stored_game.instance_id == "client-controlled"
    assert is_binary(stored_game.instance_id)
  end

  test "legacy persisted games without instance identity are upgraded during restore" do
    pin = "L" <> Integer.to_string(System.unique_integer([:positive]))

    assert {:ok, _snapshot, host_token} =
             Games.create_session(%{
               "pin" => pin,
               "host_id" => "host_test",
               "quiz_id" => "quiz_test",
               "questions" => [question()],
               "game_mode" => "classic"
             })

    assert {:ok, _joined, _player_token, _player_id} =
             Games.join_player(pin, %{"nickname" => "Mia", "avatar" => "🦊"})

    assert {:ok, _active} = Games.start_game(pin, host_token)
    assert {:ok, stored_game} = QuizworldRealtime.TestGameStore.fetch_game(pin)
    legacy_game = Map.delete(stored_game, :instance_id)
    :ok = QuizworldRealtime.TestGameStore.persist_game(legacy_game)

    [{pid, _value}] = Registry.lookup(QuizworldRealtime.GameRegistry, pin)
    :ok = DynamicSupervisor.terminate_child(QuizworldRealtime.GameSupervisor, pid)
    assert_game_stopped(pin)

    assert {:ok, recovered} = Games.snapshot(pin)
    assert recovered.status == "active"
    assert length(recovered.players) == 1
    assert {:ok, upgraded_game} = QuizworldRealtime.TestGameStore.fetch_game(pin)
    assert is_binary(upgraded_game.instance_id)
  end

  test "an abnormal GameServer restart restores the latest game state" do
    pin = "R" <> Integer.to_string(System.unique_integer([:positive]))

    assert {:ok, _snapshot, host_token} =
             Games.create_session(%{
               "pin" => pin,
               "host_id" => "host_test",
               "quiz_id" => "quiz_test",
               "questions" => [question()],
               "game_mode" => "classic"
             })

    assert {:ok, _joined, _player_token, _player_id} =
             Games.join_player(pin, %{"nickname" => "Mia", "avatar" => "🦊"})

    assert {:ok, active_before} = Games.start_game(pin, host_token)
    [{pid, _value}] = Registry.lookup(QuizworldRealtime.GameRegistry, pin)
    monitor = Process.monitor(pid)
    Process.exit(pid, :kill)

    assert_receive {:DOWN, ^monitor, :process, ^pid, :killed}, 1_000
    restarted_pid = await_restarted_game(pin, pid)
    assert Process.alive?(restarted_pid)

    assert {:ok, recovered} = Games.snapshot(pin)
    assert recovered.status == "active"
    assert length(recovered.players) == 1
    assert recovered.question_started_at == active_before.question_started_at
  end

  test "a store-restored game uses the latest state on a later crash" do
    pin = "D" <> Integer.to_string(System.unique_integer([:positive]))

    assert {:ok, _snapshot, host_token} =
             Games.create_session(%{
               "pin" => pin,
               "host_id" => "host_test",
               "quiz_id" => "quiz_test",
               "questions" => [question()],
               "game_mode" => "classic"
             })

    assert {:ok, _joined, player_token, player_id} =
             Games.join_player(pin, %{"nickname" => "Mia", "avatar" => "🦊"})

    assert {:ok, _active} = Games.start_game(pin, host_token)
    [{first_pid, _value}] = Registry.lookup(QuizworldRealtime.GameRegistry, pin)
    :ok = DynamicSupervisor.terminate_child(QuizworldRealtime.GameSupervisor, first_pid)
    assert_game_stopped(pin)

    assert {:ok, restored_active} = Games.snapshot(pin)
    assert restored_active.status == "active"
    [{restored_pid, _value}] = Registry.lookup(QuizworldRealtime.GameRegistry, pin)

    assert {:ok, revealed} = Games.submit_answer(pin, player_id, player_token, "a1", 0)
    assert revealed.status == "reveal"

    monitor = Process.monitor(restored_pid)
    Process.exit(restored_pid, :kill)
    assert_receive {:DOWN, ^monitor, :process, ^restored_pid, :killed}, 1_000
    _latest_pid = await_restarted_game(pin, restored_pid)

    assert {:ok, recovered_reveal} = Games.snapshot(pin)
    assert recovered_reveal.status == "reveal"
    assert length(recovered_reveal.current_answers) == 1
  end

  test "a game transition publishes exactly one session update" do
    pin = "T" <> Integer.to_string(System.unique_integer([:positive]))
    topic = Games.topic(pin)
    Phoenix.PubSub.subscribe(QuizworldRealtime.PubSub, topic)

    assert {:ok, _snapshot, _host_token} =
             Games.create_session(%{
               "pin" => pin,
               "host_id" => "host_test",
               "quiz_id" => "quiz_test",
               "questions" => [question()],
               "game_mode" => "classic"
             })

    assert_receive {:session_updated, _created_snapshot}

    assert {:ok, joined_snapshot, _player_token, _player_id} =
             Games.join_player(pin, %{"nickname" => "Mia", "avatar" => "🦊"})

    assert_receive {:session_updated, ^joined_snapshot}
    refute_receive {:session_updated, ^joined_snapshot}, 100
  end

  test "player readiness is persisted and broadcast to the lobby" do
    pin = "Y" <> Integer.to_string(System.unique_integer([:positive]))
    Phoenix.PubSub.subscribe(QuizworldRealtime.PubSub, Games.topic(pin))

    assert {:ok, _snapshot, _host_token} =
             Games.create_session(%{
               "pin" => pin,
               "host_id" => "host_test",
               "quiz_id" => "quiz_test",
               "questions" => [question()],
               "game_mode" => "classic"
             })

    assert_receive {:session_updated, _created_snapshot}

    assert {:ok, _joined, player_token, player_id} =
             Games.join_player(pin, %{"nickname" => "Mia", "avatar" => "🦊"})

    assert_receive {:session_updated, _joined_snapshot}
    assert {:ok, ready_snapshot} = Games.ready_player(pin, player_id, player_token)
    assert ready_snapshot.ready_player_ids == [player_id]
    assert_receive {:session_updated, ^ready_snapshot}
  end

  test "the last eligible answer reveals the round on the server" do
    pin = "A" <> Integer.to_string(System.unique_integer([:positive]))

    assert {:ok, _snapshot, host_token} =
             Games.create_session(%{
               "pin" => pin,
               "host_id" => "host_test",
               "quiz_id" => "quiz_test",
               "questions" => [question()],
               "game_mode" => "classic"
             })

    assert {:ok, _joined, player_token, player_id} =
             Games.join_player(pin, %{"nickname" => "Mia", "avatar" => "🦊"})

    assert {:ok, _active} = Games.start_game(pin, host_token)

    assert {:ok, revealed} =
             Games.submit_answer(pin, player_id, player_token, "a1", 0)

    assert revealed.status == "reveal"
    assert length(revealed.current_answers) == 1
  end

  test "normal cleanup removes a game without restarting it" do
    pin = "C" <> Integer.to_string(System.unique_integer([:positive]))

    assert {:ok, _snapshot, _host_token} =
             Games.create_session(%{
               "pin" => pin,
               "host_id" => "host_test",
               "quiz_id" => "quiz_test",
               "questions" => [question()],
               "game_mode" => "classic"
             })

    [{pid, _value}] = Registry.lookup(QuizworldRealtime.GameRegistry, pin)
    monitor = Process.monitor(pid)
    send(pid, :session_cleanup)

    assert_receive {:DOWN, ^monitor, :process, ^pid, :normal}, 1_000
    assert_game_stopped(pin)
  end

  describe "topic/1" do
    test "generates a valid pubsub topic" do
      assert Games.topic("ABC123") == "game:ABC123"
    end

    test "sanitizes colons from pin" do
      assert Games.topic("AB:C12:3") == "game:ABC123"
    end

    test "sanitizes asterisks from pin" do
      assert Games.topic("ABC*123") == "game:ABC123"
    end

    test "sanitizes whitespace from pin" do
      assert Games.topic("AB C 12 3") == "game:ABC123"
    end

    test "truncates overly long pins" do
      long_pin = String.duplicate("A", 100)
      topic = Games.topic(long_pin)
      assert String.length(topic) <= 48
      assert String.starts_with?(topic, "game:")
    end
  end

  describe "sanitize_pin/1" do
    test "uppercases and sanitizes pin" do
      assert Games.sanitize_pin("abc123") == "ABC123"
    end

    test "removes colons, asterisks, and whitespace" do
      assert Games.sanitize_pin("AB:C* 12 3") == "ABC123"
    end

    test "truncates to max 20 characters" do
      assert String.length(Games.sanitize_pin(String.duplicate("A", 50))) == 20
    end

    test "handles integer input" do
      assert Games.sanitize_pin(123_456) == "123456"
    end

    test "handles nil gracefully" do
      assert Games.sanitize_pin(nil) == ""
    end
  end
end
